import { geoArea, geoCentroid } from 'd3-geo';
import isoCountries from 'i18n-iso-countries';
import type { Feature, MultiPolygon, Polygon } from 'geojson';
// Simplified 1:50m borders with the large lakes cut out, generated by scripts/build-borders.mjs.
import shapes from '../data/countries.json';

export interface Country {
  /** ISO 3166 alpha-3 code ("JPN"), or a made-up "X-..." key for the few shapes without one. */
  iso: string;
  name: string;
  /** ISO alpha-2 code, used for the flag image. */
  alpha2?: string;
  /** For an overseas territory split out of its country (French Guiana), that country's iso. */
  parent?: string;
  feature: Feature<Polygon | MultiPolygon>;
  /** Where the photo bubble sits: the centre of the country's largest landmass. */
  lat: number;
  lng: number;
}

// Shapes Natural Earth ships without an ISO numeric code, or sharing one with another shape.
const SPECIAL: Record<string, { iso: string; alpha2?: string }> = {
  Kosovo: { iso: 'XKX', alpha2: 'XK' },
  'Ashmore and Cartier Is.': { iso: 'X-ASHMORE-AND-CARTIER', alpha2: 'AU' },
};

/** Flag as an HTML string, for places that need raw HTML (the globe tooltip). Windows can't draw flag emoji, so these are SVGs. */
export function flagHtml(c: Country) {
  return c.alpha2 ? `<span class="fi fi-${c.alpha2.toLowerCase()} flag"></span>` : '<span class="flag">🏳️</span>';
}

function mainLandmass(f: Feature<Polygon | MultiPolygon>): Feature<Polygon> {
  if (f.geometry.type === 'Polygon') return f as Feature<Polygon>;
  const parts = f.geometry.coordinates.map(
    (coordinates): Feature<Polygon> => ({ type: 'Feature', properties: {}, geometry: { type: 'Polygon', coordinates } }),
  );
  return parts.reduce((a, b) => (geoArea(b) > geoArea(a) ? b : a));
}

type Shape = { id: string | null; name: string; polygons: number[][][][]; iso?: string; alpha2?: string; parent?: string };

export const COUNTRIES: Country[] = (shapes as Shape[])
  .map(({ id: rawId, name, polygons, ...territory }) => {
    const f: Feature<MultiPolygon> = { type: 'Feature', properties: {}, geometry: { type: 'MultiPolygon', coordinates: polygons } };
    const id = rawId ?? undefined;
    const special = SPECIAL[name];
    const iso = territory.iso ?? special?.iso ?? (id && isoCountries.numericToAlpha3(id)) ?? `X-${name.replace(/[^A-Za-z]+/g, '-').toUpperCase()}`;
    const alpha2 = territory.alpha2 ?? special?.alpha2 ?? (id ? isoCountries.numericToAlpha2(id) : undefined);
    const [lng, lat] = geoCentroid(mainLandmass(f));
    return { iso, name, alpha2, parent: territory.parent, feature: f, lat, lng };
  })
  .sort((a, b) => a.name.localeCompare(b.name));

const BY_ISO = new Map(COUNTRIES.map((c) => [c.iso, c]));

export const getCountry = (iso: string | undefined) => (iso ? BY_ISO.get(iso) : undefined);

/** Overseas territories of a country (France → French Guiana, Réunion…). */
export const territoriesOf = (iso: string) => COUNTRIES.filter((c) => c.parent === iso);

/** Country codes to search places in: a territory's own plus its parent's, as map services file some under either. */
export function searchCodes(c: Country) {
  const codes = [c.alpha2, getCountry(c.parent)?.alpha2].filter((a): a is string => !!a && a !== 'IC');
  return [...new Set(codes)].join(',').toLowerCase() || undefined;
}
